apiVersion: v1
kind: Service
metadata:
  name: datanode1
  labels:
    microservice: datanode1
spec:
  clusterIP: "None" 
  ports:
    - port: 9864
      targetPort: 9864
  selector:
    microservice: datanode1
---
apiVersion: v1
kind: Service
metadata:
  name: datanode-ui
  labels:
    microservice: datanode-ui
spec:
  type: LoadBalancer
  ports:
    - port: 9864
      targetPort: 9864
  selector:
    microservice: datanode1
