apiVersion: apps/v1
kind: Deployment
metadata:
 name: jupyter-notebook
spec:
 strategy:
   rollingUpdate:
     maxSurge: 1
     maxUnavailable: 1
   type: RollingUpdate
 replicas: 1
 selector:
   matchLabels:
     app: jupyter-notebook
 template:
   metadata:
     labels:
       app: jupyter-notebook
   spec:
     containers:
       - name: jupyter-notebook
         image: tx640/jupyter:v1
         ports:
           - containerPort: 8888
