apiVersion: apps/v1
apiVersion: v1
kind: Service
metadata:
  labels:
    app: jupyter-notebook
  name: jupyter-notebook
spec:
  ports:
    - port: 8888
      protocol: TCP
      targetPort: 8888
      nodePort: 30088
  selector:
    app: jupyter-notebook
  type: NodePort
