apiVersion: apps/v1
apiVersion: v1
kind: Service
metadata:
  labels:
    app: spark
  name: spark
spec:
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
      nodePort: 30080
  selector:
    app: spark
  type: NodePort
