apiVersion: v1
kind: Service              
metadata:
  name: spark
spec:
  type: LoadBalancer
  loadBalancerIP: 34.174.183.197       
  ports:
  - port: 8080
    protocol: TCP          
    targetPort: 8080         
  selector:                
    app: spark
